const double birdStartX = 100;
const double birdStartY = 100;
const double birdwidth = 60;
const double birdheight = 40;
const double jumpStrength = -300;
const double gravity = 800;
const double groundHeight = 100;
const double PipeInterval = 2;
const double PipeGap = 200;
const double minPipeHeight = 50;
const double pipeWidth = 60;
const minRockHeight = 25;
const maxRockHeight = 25;
const minBushHeight = 25;
const maxBushHeight = 25;
const minGrassHeight = 25;
const maxGrassHeight = 25;

double groundSpeed = 100;